# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13_Q3aDpBcDPLTLvMZs4rlcPk5j1nxdNl
"""

import streamlit as st
from PIL import Image
from datetime import date
import torch
import torchvision.transforms as transforms
from densenet121_lstm import load_model_and_tokenizer, generate_caption
import os

# Load model
model, tokenizer = load_model_and_tokenizer("fold_4_best_model.pth", device='cpu')

# Image transform (harus sesuai dengan preprocessing waktu training)
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
])

# Page configuration
st.set_page_config(page_title="Deteksi dan Captioning Retinopati Diabetik", layout="centered")
st.title("🩺 Retinopati DiabeTEST")

# Input Form
with st.form("fundus_form"):
    nama_pasien = st.text_input("Nama Pasien")
    tanggal_lahir = st.date_input("Tanggal Lahir Pasien", min_value=date(1900, 1, 1))
    dokter = st.selectbox("Dokter Mata yang Bertugas", ["Dr Andi", "Dr Anggun"])
    uploaded_image = st.file_uploader("Unggah Citra Fundus", type=["jpg", "jpeg", "png"])

    submitted = st.form_submit_button("Prediksi")

# Output
if submitted and uploaded_image is not None:
    image = Image.open(uploaded_image).convert("RGB")
    st.image(image, caption="Citra Fundus yang Diunggah", use_column_width=True)

    # Hitung usia
    today = date.today()
    usia = today.year - tanggal_lahir.year - ((today.month, today.day) < (tanggal_lahir.month, tanggal_lahir.day))

    # Transform & Caption
    input_tensor = transform(image).unsqueeze(0)
    caption = generate_caption(model, tokenizer, input_tensor)

    # Rekomendasi
    if "tidak ada lesi" in caption.lower():
        rekomendasi = "Mata Normal"
    else:
        rekomendasi = "Pasien Terindikasi DR, disarankan Pengobatan Lebih Lanjut"

    # Output
    st.subheader("📝 Hasil Analisis")
    st.write(f"**Nama Pasien:** {nama_pasien}")
    st.write(f"**Usia Pasien:** {usia} tahun")
    st.write(f"**Dokter Mata:** {dokter}")
    st.write(f"**Caption Fundus:** _{caption}_")
    st.write(f"**Rekomendasi:** {rekomendasi}")